#!.venv/bin/python3

import os
import json
import platform
import subprocess
import hashlib
from datetime import datetime
from flask import Flask, render_template, jsonify, request, send_from_directory
import tkinter as tk
from tkinter import filedialog
import boto3
from botocore.exceptions import NoCredentialsError, ClientError
from PIL import Image

app = Flask(__name__, static_folder='.', static_url_path='')

APP_DIR = os.path.dirname(os.path.abspath(__file__))
DATASETS_DIR = os.path.join(APP_DIR, 'datasets')

# Single object-detection class (many instances per frame are fine).
CLASS_NAMES = ["airplane"]

# Ordered keypoints for the pose model. The position in this list IS the keypoint
# index written into the YOLO label file (YOLO stores slots, not names).
KP_ORDER = [
    "nose", "left_wing_tip", "right_wing_tip", "tail_top_corner",
    "left_landing_gear", "right_landing_gear", "nose_gear"
]
NUM_KP = len(KP_ORDER)
# Left/right swap map for horizontal-flip augmentation (Ultralytics flip_idx).
KP_FLIP_IDX = [0, 2, 1, 3, 5, 4, 6]

IMAGE_EXTS = ('.jpg', '.jpeg', '.png', '.bmp', '.webp')
DATA_YAML = 'data.yaml'
METADATA_FILE = 'metadata.json'  # holds per-image tags + save timestamps (not labels)


def open_native_folder_browser():
    if platform.system() == "Darwin":
        try:
            cmd = ['osascript', '-e', 'POSIX path of (choose folder with prompt "Select Workspace Folder:")']
            return subprocess.check_output(cmd, stderr=subprocess.DEVNULL).decode('utf-8').strip()
        except subprocess.CalledProcessError: return None
    else:
        root = tk.Tk()
        root.withdraw()
        root.attributes('-topmost', True)
        path = filedialog.askdirectory()
        root.destroy()
        return path


# ---------------------------------------------------------------------------
# YOLO label helpers
# ---------------------------------------------------------------------------

def label_path_for(workspace, image_filename):
    return os.path.join(workspace, os.path.splitext(image_filename)[0] + '.txt')


def write_data_yaml(workspace):
    """Write the Ultralytics dataset descriptor describing classes + keypoints."""
    lines = [
        "# FyveBy Aircraft Keypoint Dataset (YOLO pose format)",
        "# Auto-generated by label_app.py -- edit class/keypoint config there.",
        "path: .",
        "train: .",
        "val: .",
        "",
        "names:",
    ]
    lines += [f"  {i}: {name}" for i, name in enumerate(CLASS_NAMES)]
    lines += [
        "",
        f"kpt_shape: [{NUM_KP}, 3]",
        f"flip_idx: {KP_FLIP_IDX}",
        "# Keypoint slot order (YOLO uses index position only, names are for reference):",
        "# " + ", ".join(f"{i}:{name}" for i, name in enumerate(KP_ORDER)),
    ]
    with open(os.path.join(workspace, DATA_YAML), 'w') as f:
        f.write("\n".join(lines) + "\n")


def load_metadata(workspace):
    path = os.path.join(workspace, METADATA_FILE)
    if os.path.exists(path):
        try:
            with open(path) as f: return json.load(f)
        except Exception: return {}
    return {}


def save_metadata(workspace, meta):
    with open(os.path.join(workspace, METADATA_FILE), 'w') as f:
        json.dump(meta, f, indent=2)


def _clamp01(v):
    return min(1.0, max(0.0, v))


def commit_save_to_yolo(workspace, filename, bboxes, keypoints, tags, img_w, img_h):
    """Write one YOLO pose label file (<image>.txt). One line per instance:
    `cls cx cy w h px1 py1 v1 ... px7 py7 v7`, all box/point coords normalized.
    Keypoints are assigned to whichever box contains them; absent slots are zeroed.
    Tags + timestamp are kept in metadata.json (YOLO has no slot for them)."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    img_w = float(img_w) or 1.0
    img_h = float(img_h) or 1.0

    lines = []
    for box in bboxes:
        x1, x2 = min(box['x1'], box['x2']), max(box['x1'], box['x2'])
        y1, y2 = min(box['y1'], box['y2']), max(box['y1'], box['y2'])
        cls = CLASS_NAMES.index(box['label']) if box.get('label') in CLASS_NAMES else 0
        parts = [
            str(cls),
            f"{_clamp01((x1 + x2) / 2 / img_w):.6f}",
            f"{_clamp01((y1 + y2) / 2 / img_h):.6f}",
            f"{_clamp01((x2 - x1) / img_w):.6f}",
            f"{_clamp01((y2 - y1) / img_h):.6f}",
        ]
        slots = [(0.0, 0.0, 0)] * NUM_KP
        for kp in keypoints:
            if x1 <= kp['x'] <= x2 and y1 <= kp['y'] <= y2 and kp['label'] in KP_ORDER:
                idx = KP_ORDER.index(kp['label'])
                slots[idx] = (_clamp01(kp['x'] / img_w), _clamp01(kp['y'] / img_h), int(kp.get('visibility', 2)))
        for kx, ky, kv in slots:
            parts += [f"{kx:.6f}", f"{ky:.6f}", str(kv)]
        lines.append(" ".join(parts))

    with open(label_path_for(workspace, filename), 'w') as f:
        f.write("\n".join(lines) + ("\n" if lines else ""))

    meta = load_metadata(workspace)
    meta[filename] = {"tags": tags, "date": timestamp}
    save_metadata(workspace, meta)

    if not os.path.exists(os.path.join(workspace, DATA_YAML)):
        write_data_yaml(workspace)
    return timestamp


def parse_yolo_label_file(txt_path, img_w, img_h):
    """Parse a YOLO pose label file back into pixel-space app structures."""
    bboxes, keypoints = [], []
    if not os.path.exists(txt_path):
        return bboxes, keypoints
    with open(txt_path) as f:
        for raw in f:
            parts = raw.strip().split()
            if not parts:
                continue
            try:
                vals = [float(p) for p in parts]
            except ValueError:
                continue
            cls = int(vals[0])
            cx, cy = vals[1] * img_w, vals[2] * img_h
            bw, bh = vals[3] * img_w, vals[4] * img_h
            label = CLASS_NAMES[cls] if 0 <= cls < len(CLASS_NAMES) else CLASS_NAMES[0]
            bboxes.append({"x1": cx - bw / 2, "y1": cy - bh / 2,
                           "x2": cx + bw / 2, "y2": cy + bh / 2, "label": label})
            kp_vals = vals[5:]
            for i in range(NUM_KP):
                base = i * 3
                if base + 2 < len(kp_vals):
                    kx, ky, kv = kp_vals[base], kp_vals[base + 1], int(kp_vals[base + 2])
                    if kv > 0:
                        keypoints.append({"x": kx * img_w, "y": ky * img_h,
                                          "label": KP_ORDER[i], "visibility": kv})
    return bboxes, keypoints


def load_yolo_annotations(workspace):
    """Build the in-app annotation store from per-image YOLO .txt files."""
    meta = load_metadata(workspace)
    app_store = {}
    images = [f for f in os.listdir(workspace) if f.lower().endswith(IMAGE_EXTS)]
    for fname in images:
        bboxes, keypoints = [], []
        txt = label_path_for(workspace, fname)
        if os.path.exists(txt):
            try:
                with Image.open(os.path.join(workspace, fname)) as im:
                    w, h = im.size
                bboxes, keypoints = parse_yolo_label_file(txt, w, h)
            except Exception:
                pass
        m = meta.get(fname, {})
        app_store[fname] = {
            "bboxes": bboxes, "keypoints": keypoints,
            "tags": m.get("tags", []), "date": m.get("date", "Not annotated yet")
        }
    return app_store


def calculate_local_file_md5(file_path):
    hasher = hashlib.md5()
    with open(file_path, 'rb') as f:
        for chunk in iter(lambda: f.read(4096), b''): hasher.update(chunk)
    return f'"{hasher.hexdigest()}"'


# ---------------------------------------------------------------------------
# S3 sync helpers
# ---------------------------------------------------------------------------

def parse_s3_uri(s3_uri):
    s3_uri = s3_uri.strip()
    if s3_uri.lower().startswith('s3://'):
        s3_uri = s3_uri[5:]
    parts = s3_uri.split('/', 1)
    bucket = parts[0]
    prefix = (parts[1].strip() if len(parts) > 1 else '').strip('/')
    return bucket, prefix


def local_dir_for_uri(bucket, prefix):
    """Derive the local dataset folder (label_app/datasets/<bucket>[_<prefix>])."""
    name = bucket + ('_' + prefix.replace('/', '_') if prefix else '')
    safe = "".join(c if (c.isalnum() or c in '-_.') else '_' for c in name)
    return os.path.join(DATASETS_DIR, safe)


def s3_key_for(prefix, rel):
    rel = rel.replace('\\', '/')
    return f"{prefix}/{rel}" if prefix else rel


def list_s3_objects(s3_client, bucket, prefix):
    """Return {relative_path: {Key, ETag}} for every object under the prefix."""
    objs = {}
    paginator = s3_client.get_paginator('list_objects_v2')
    kwargs = {'Bucket': bucket}
    if prefix:
        kwargs['Prefix'] = prefix + '/'
    for page in paginator.paginate(**kwargs):
        for obj in page.get('Contents', []):
            key = obj['Key']
            if key.endswith('/'):
                continue
            rel = key[len(prefix) + 1:] if prefix else key
            if rel:
                objs[rel] = {"Key": key, "ETag": obj.get('ETag')}
    return objs


def list_local_files(local_dir):
    """Return {relative_path: absolute_path} for every (non-hidden) file."""
    out = {}
    for root, _dirs, files in os.walk(local_dir):
        for fn in files:
            if fn.startswith('.'):
                continue
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, local_dir).replace('\\', '/')
            out[rel] = full
    return out


def pull_bucket(s3_client, bucket, prefix, local_dir):
    """Download every object under the prefix into local_dir (preserving layout)."""
    os.makedirs(local_dir, exist_ok=True)
    objs = list_s3_objects(s3_client, bucket, prefix)
    for rel, info in objs.items():
        dest = os.path.join(local_dir, rel)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        s3_client.download_file(bucket, info['Key'], dest)
    if not os.path.exists(os.path.join(local_dir, DATA_YAML)):
        write_data_yaml(local_dir)
    return len(objs)


def push_local(s3_client, bucket, prefix, local_dir, do_delete):
    """Upload changed local files; optionally delete S3 objects missing locally."""
    local_files = list_local_files(local_dir)
    s3_objs = list_s3_objects(s3_client, bucket, prefix)

    uploaded, skipped = 0, 0
    for rel, full in local_files.items():
        existing = s3_objs.get(rel)
        if existing and existing.get('ETag') == calculate_local_file_md5(full):
            skipped += 1
            continue
        s3_client.upload_file(full, bucket, s3_key_for(prefix, rel))
        uploaded += 1

    to_delete = [rel for rel in s3_objs if rel not in local_files]
    deleted = 0
    if do_delete:
        for rel in to_delete:
            s3_client.delete_object(Bucket=bucket, Key=s3_objs[rel]['Key'])
            deleted += 1
    return {
        "uploaded": uploaded, "skipped": skipped, "to_delete": to_delete,
        "deleted": deleted, "local_count": len(local_files), "cloud_count": len(s3_objs),
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.route('/')
def home():
    return render_template('index.html')


@app.route('/select_folder', methods=['POST'])
def select_folder():
    target_path = open_native_folder_browser()
    if not target_path: return jsonify({"status": "cancelled"})
    image_list = [f for f in os.listdir(target_path) if f.lower().endswith(IMAGE_EXTS)]
    return jsonify({"folder": target_path, "images": image_list,
                    "annotations": load_yolo_annotations(target_path)})


@app.route('/image/<path:filename>')
def serve_image(filename):
    workspace = request.args.get('workspace')
    if not workspace or not os.path.exists(workspace): return "Missing space parameter query profile", 400
    return send_from_directory(workspace, filename)


@app.route('/save', methods=['POST'])
def save():
    payload = request.json
    workspace = payload.get('workspace')
    if not workspace: return jsonify({"status": "error", "message": "Missing active workspace token."}), 400
    try:
        timestamp = commit_save_to_yolo(
            workspace, payload.get('filename'), payload.get('bboxes', []),
            payload.get('keypoints', []), payload.get('tags', []),
            payload.get('image_width', 1920), payload.get('image_height', 1080)
        )
        return jsonify({"status": "success", "date": timestamp})
    except Exception as e: return jsonify({"status": "error", "message": str(e)}), 500


@app.route('/delete_image', methods=['POST'])
def delete_image():
    payload = request.json
    workspace = payload.get('workspace')
    filename = payload.get('filename')
    target = os.path.join(workspace, filename)
    if os.path.exists(target): os.remove(target)
    txt = label_path_for(workspace, filename)
    if os.path.exists(txt): os.remove(txt)
    meta = load_metadata(workspace)
    if filename in meta:
        del meta[filename]
        save_metadata(workspace, meta)
    return jsonify({"status": "success"})


@app.route('/transform_image', methods=['POST'])
def transform_image():
    payload = request.json
    workspace = payload.get('workspace')
    filename = payload.get('filename')
    action = payload.get('action')
    tags = payload.get('tags', [])
    incoming_bboxes = payload.get('bboxes', [])
    incoming_keypoints = payload.get('keypoints', [])

    img_path = os.path.join(workspace, filename)
    try:
        with Image.open(img_path) as img:
            orig_w, orig_h = img.size
            if action == 'crop':
                coords = payload.get('coords')
                x1, y1 = max(0, int(coords[0])), max(0, int(coords[1]))
                x2, y2 = min(orig_w, int(coords[2])), min(orig_h, int(coords[3]))
                crop_w, crop_h = x2 - x1, y2 - y1

                for box in incoming_bboxes:
                    bx1, by1, bx2, by2 = box['x1'], box['y1'], box['x2'], box['y2']
                    if not (bx2 <= x1 or bx1 >= x2 or by2 <= y1 or by1 >= y2) and not (bx1 >= x1 and bx2 <= x2 and by1 >= y1 and by2 <= y2):
                        return jsonify({"status": "error", "message": f"Crop Rejected: This custom selection slice splits through the instance box labeled '{box['label']}'."}), 400

                img.crop((x1, y1, x2, y2)).save(img_path)
                transformed_bboxes = [{"x1": max(0, b['x1'] - x1), "y1": max(0, b['y1'] - y1), "x2": min(crop_w, b['x2'] - x1), "y2": min(crop_h, b['y2'] - y1), "label": b['label']} for b in incoming_bboxes if min(crop_w, b['x2'] - x1) > max(0, b['x1'] - x1)]
                transformed_keypoints = [{"x": k['x'] - x1, "y": k['y'] - y1, "label": k['label'], "visibility": k['visibility']} for k in incoming_keypoints if 0 <= (k['x'] - x1) <= crop_w and 0 <= (k['y'] - y1) <= crop_h]

                timestamp = commit_save_to_yolo(workspace, filename, transformed_bboxes, transformed_keypoints, tags, crop_w, crop_h)
                return jsonify({"status": "success", "bboxes": transformed_bboxes, "keypoints": transformed_keypoints, "date": timestamp})

            elif action == 'resize':
                target_w = int(payload.get('width'))
                ratio = target_w / orig_w
                target_h = int(orig_h * ratio)
                img.resize((target_w, target_h), Image.Resampling.LANCZOS).save(img_path)
                transformed_bboxes = [{"x1": b['x1']*ratio, "y1": b['y1']*ratio, "x2": b['x2']*ratio, "y2": b['y2']*ratio, "label": b['label']} for b in incoming_bboxes]
                transformed_keypoints = [{"x": k['x']*ratio, "y": k['y']*ratio, "label": k['label'], "visibility": k['visibility']} for k in incoming_keypoints]

                timestamp = commit_save_to_yolo(workspace, filename, transformed_bboxes, transformed_keypoints, tags, target_w, target_h)
                return jsonify({"status": "success", "bboxes": transformed_bboxes, "keypoints": transformed_keypoints, "date": timestamp})
    except Exception as e: return jsonify({"status": "error", "message": str(e)}), 500


@app.route('/sync_s3', methods=['POST'])
def sync_s3():
    """S3 sync. If the local dataset dir for this URI is missing/empty -> PULL the
    whole bucket into label_app/datasets/<bucket>. If it already exists -> PUSH local
    up to the cloud. When the bucket holds files the local folder no longer has, we
    do NOT delete on the first pass: we return a warning comparing file counts and
    only delete from S3 (local is source of truth) once the user re-confirms."""
    payload = request.json
    s3_uri = payload.get('s3_uri', '').strip()
    confirm_delete = bool(payload.get('confirm_delete', False))

    if not s3_uri:
        return jsonify({"status": "error", "message": "Missing S3 URI parameter field."}), 400
    bucket, prefix = parse_s3_uri(s3_uri)
    if not bucket:
        return jsonify({"status": "error", "message": "Could not parse a bucket name from the S3 URI."}), 400

    local_dir = local_dir_for_uri(bucket, prefix)
    pretty_uri = f"s3://{bucket}/{prefix}" if prefix else f"s3://{bucket}"

    try:
        s3_client = boto3.client('s3')

        # CASE A -- nothing local yet: pull the bucket down and open it.
        if not os.path.isdir(local_dir) or not os.listdir(local_dir):
            count = pull_bucket(s3_client, bucket, prefix, local_dir)
            images = [f for f in os.listdir(local_dir) if f.lower().endswith(IMAGE_EXTS)]
            return jsonify({
                "status": "pulled", "folder": local_dir, "images": images,
                "annotations": load_yolo_annotations(local_dir),
                "message": f"Pulled {count} object(s) from {pretty_uri} into:\n{local_dir}"
            })

        # CASE B -- local dir exists: push local up to the cloud.
        result = push_local(s3_client, bucket, prefix, local_dir, confirm_delete)

        if result["to_delete"] and not confirm_delete:
            n = len(result["to_delete"])
            return jsonify({
                "status": "confirm_delete",
                "local_count": result["local_count"],
                "cloud_count": result["cloud_count"],
                "delete_count": n,
                "message": (
                    "DELETE WARNING -- file counts differ between local and S3.\n\n"
                    f"Local folder : {result['local_count']} files\n"
                    f"S3 bucket    : {result['cloud_count']} files\n\n"
                    f"Uploaded {result['uploaded']} changed file(s).\n"
                    f"{n} file(s) exist in S3 but NOT locally.\n\n"
                    f"Confirm to DELETE those {n} file(s) from {pretty_uri} so the bucket "
                    "mirrors your local folder. This is IRREVERSIBLE."
                )
            })

        msg = f"Sync complete.\nUploaded {result['uploaded']}, skipped {result['skipped']} unchanged."
        if result["deleted"]:
            msg += f"\nDeleted {result['deleted']} file(s) from S3 to mirror local."
        cloud_after = result["cloud_count"] - result["deleted"]
        msg += f"\n\nLocal: {result['local_count']} files  |  S3: {cloud_after} files"
        return jsonify({"status": "success", "message": msg})

    except NoCredentialsError:
        return jsonify({"status": "error", "message": "AWS credentials not found. Run `aws configure` first."}), 500
    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


if __name__ == '__main__':
    app.run(port=5000, debug=True)
